# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.3
loader_version=0.19.5

# Mod Properties
mod_version=0.13.6
maven_group=org.provim
archives_base_name=nylon

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.160.5+26.3
polymer_version=0.18.0+26.3-rc-1
